name: "windows powershell CI workflow "


on:
  push:
    branches: [ test ]



jobs:

  windows-latest-pwsh-scripts:
    name: "pwsh scripts - windows-latest "  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: "powershell version" 
      run: |
        $PSVersionTable
        pwsh                              
    - name: "test verbose" 
      run: .\scripts\Test_Verbose.ps1
      shell: pwsh    
    - name: "windows version" 
      run: .\scripts\Windows_Version.ps1
      shell: pwsh  
    - name: "chrome - silent uninstall " 
      run: .\scripts\uninstall_chrome.ps1
      shell: pwsh 
    - name: "chrome - silent install " 
      run: .\scripts\install_chrome.ps1
      shell: pwsh       
    - name: "chrome - clear https cache" 
      run: .\scripts\clear_chrome_https_cache.ps1
      shell: pwsh       
