name: "execution policy CI workflow "


on:
  push:
    branches: [ test ]



jobs:

  windows-latest-pwsh-scripts:
    name: "pwsh scripts - windows-latest "  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: "powershell version" 
      run: |
        $PSVersionTable
        pwsh                              

    - name: "test verbose" 
      run: .\scripts\Test_Verbose.ps1
      shell: pwsh    

    - name: "windows version" 
      run: .\scripts\Windows_Version.ps1
      shell: pwsh  

    - name: "retrieves and sets the execution policy for the script runner " 
      run: '.\scripts\retrieves and sets the execution policy for the script runner.ps1'
      shell: pwsh 
     
